name: Hat
version: ${project.version}
main: me.thealmightyshibe.hat.Main
api-version: 1.16
authors: [ TheAlmightyShibe ]
description: You can now put any item on your head! Wow!
commands:
  nick:
    description: Gives a nick to a player
    usage: /<command>
  unnick:
    description: Unnicks a player
    usage: /<command>
  hatinfo:
    description: useless command
    usage: /<commmand>


